### ISSUE TITLE
there is no mtranslate package

### ISSUE THREAD

**Issue by sajjjadayobi** [borhenryk/train_custom_qa_model#8]
thanks for your great job, where the **mtranslate** package comes from?
I have an error during importing

**Comment by borhenryk** [comment]
Mtranslate is from Google but they exchanged the api and the package is not maintained anymore. Best thing would be to exchange the mtranslate parts with the translating pipeline from huggingface transformers and use one of the helsinki models for a specific language :) have no time at the moment but feel free to change it in code and do a pull request!
